### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by anhwaivo** [Its-VrxxDev/zlapi#7]
---

## Description of the problem
cant login

## Code to reproduce
```py
client = Client(API_KEY, SECRET_KEY, IMEI, SESSION_COOKIES)
client.listen(run_forever=True, type='requests')
```

## Traceback
```
 DEBUG  Logging in None...
Traceback (most recent call last):
  File "/root/zabot2/zlapi/_state.py", line 74, in login
    raise _exception.ZaloLoginError(f"Error #{error} when logging in: {content}")
zlapi._exception.ZaloLoginError: Error #None when logging in: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/zabot2/main.py", line 109, in <module>
    client = Client(API_KEY, SECRET_KEY, IMEI, SESSION_COOKIES)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/zabot2/main.py", line 14, in __init__
    super().__init__(api_key, secret_key, imei=imei, session_cookies=session_cookies)
  File "/root/zabot2/zlapi/_client.py", line 43, in __init__
    self.login(phone, password, imei, user_agent)
  File "/root/zabot2/zlapi/_client.py", line 168, in login
    self._state.login(
  File "/root/zabot2/zlapi/_state.py", line 77, in login
    raise _exception.ZaloLoginError(str(e))
zlapi._exception.ZaloLoginError: Error #None when logging in: None
```

## Environment information
- Python 3.11.2
- zlapi 1.0.2

If you have done any research, include that.
Make sure to redact all personal information.

**Comment by anhwaivo** [comment]
got another error after the recent update
```
Traceback (most recent call last):
  File "/root/zabot2/main.py", line 109, in <module>
    client = Client(API_KEY, SECRET_KEY, IMEI, SESSION_COOKIES)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/zabot2/main.py", line 14, in __init__
    super().__init__(api_key, secret_key, imei=imei, session_cookies=session_cookies)
  File "/usr/local/lib/python3.11/dist-packages/zlapi/_client.py", line 43, in __init__
    self.login(phone, password, imei, user_agent)
  File "/usr/local/lib/python3.11/dist-packages/zlapi/_client.py", line 164, in login
    raise ZaloUserError("Phone and password not set")
zlapi._exception.ZaloUserError: Phone and password not set
```

**Comment by netrotion** [comment]
This issue may helpful https://github.com/Its-VrxxDev/zlapi/issues/8

**Comment by Its-VrxxDev** [comment]
Uninstall and reinstall zlapi or you can view this issue #8
